// Behavioural test harness for transcript.js: builds a real jsdom window
// from the ACTUAL rendered page (speech_to_text.core.formatting.render_html,
// run through render_fixture.py) rather than a hand-written stand-in, so a
// refactor of transcript.js/transcript.css can be graded on behaviour - does
// the help panel still open, does the tour still count the right number of
// steps - instead of on exact source text staying byte-for-byte where a
// grep last found it.
//
// jsdom gaps this file works around, once, so individual *.test.mjs files
// don't each have to remember to:
//
//   - window.matchMedia does not exist at all. scrollBehavior() (used by
//     search's focusMatch() and the tour's own scrollIntoView call) calls
//     it directly, so its absence would throw, not just under-report
//     reduced-motion. Stubbed to "no preference" by default; a test that
//     needs reduced-motion true can reassign window.matchMedia itself after
//     buildWindow() returns, before triggering the code path that reads it.
//   - Element.prototype.scrollIntoView does not exist. Stubbed to a no-op
//     here; tests that care whether it was called replace it themselves.
//   - Element.prototype.getBoundingClientRect DOES exist, but returns all
//     zeros - jsdom does not lay pages out. Left alone here on purpose: a
//     test that needs a real-looking rect (positionDetachedMenu's clamp,
//     the tour spotlight) stubs it per-test with the specific numbers that
//     test is about, which a single shared stub here could never anticipate.
//   - navigator.clipboard and URL.createObjectURL do not exist. NOT stubbed
//     globally - only the couple of tests that exercise copy()/exportCopy()
//     need them, and a global stub would hide a real "clipboard unavailable,
//     falls back to execCommand" code path other tests might otherwise
//     exercise for free.
//   - localStorage DOES work, but only for a non-opaque origin - jsdom
//     throws SecurityError for one, and a bare `file:///transcript.html`
//     URL (matching the real app's own file:// origin) is opaque. The tests
//     therefore build against an https://transcript.test/ URL instead: nothing
//     in transcript.js branches on location.protocol, so this changes no
//     behaviour under test while making storage actually work.
//   - requestAnimationFrame DOES work, but only once pretendToBeVisual is
//     turned on (jsdom's flag for "act like a browser with a real screen",
//     which also switches on a few other visual-only globals this page
//     doesn't otherwise touch).

import { JSDOM } from 'jsdom';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = path.resolve(__dirname, '..', '..');

const PY_CANDIDATES = [process.env.HEBREW_TRANSCRIBER_PYTHON, 'python', 'py', 'python3'].filter(Boolean);

function runPython(args) {
  let lastError;
  for (const cmd of PY_CANDIDATES) {
    try {
      return execFileSync(cmd, args, { cwd: REPO_ROOT, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
    } catch (error) {
      lastError = error;
    }
  }
  throw new Error(
    `could not run render_fixture.py with any of [${PY_CANDIDATES.join(', ')}]: ${lastError && lastError.message}`
  );
}

// Cached under the OS temp dir, not inside the repo: every *.test.mjs file
// is its own `node --test` worker with its own module cache, so an
// in-memory cache in this module would not be shared across files - only a
// file the second worker can also see does that. Keyed by the newest mtime
// among the files that actually change what gets rendered, so an edit to
// transcript.js/css or the fixture builder invalidates the cache
// automatically instead of serving a stale page after every source change.
const CACHE_DIR = path.join(os.tmpdir(), 'hebrew-transcript-js-fixture-cache');

function sourceKey() {
  const watched = [
    path.join(REPO_ROOT, 'speech_to_text', 'core', 'assets', 'transcript.js'),
    path.join(REPO_ROOT, 'speech_to_text', 'core', 'assets', 'transcript.css'),
    path.join(__dirname, 'render_fixture.py'),
  ];
  const newest = Math.max(...watched.map((f) => statSync(f).mtimeMs));
  return String(Math.round(newest));
}

const FIXTURE_KINDS = new Set(['full', 'degenerate']);

/**
 * The rendered HTML for one of the two fixtures, generated by shelling out
 * to render_fixture.py and cached to disk so a full test run only pays that
 * subprocess cost once per fixture, not once per test file.
 *
 * @param {'full'|'degenerate'} kind
 * @returns {string}
 */
export function getFixtureHtml(kind) {
  if (!FIXTURE_KINDS.has(kind)) {
    throw new Error(`unknown fixture kind ${JSON.stringify(kind)}`);
  }
  mkdirSync(CACHE_DIR, { recursive: true });
  const cacheFile = path.join(CACHE_DIR, `${kind}-${sourceKey()}.html`);
  if (existsSync(cacheFile)) {
    return readFileSync(cacheFile, 'utf8');
  }
  const html = runPython(['tests/js/render_fixture.py', kind]);
  writeFileSync(cacheFile, html, 'utf8');
  return html;
}

/**
 * Builds a live jsdom window from a rendered transcript page, with
 * transcript.js's own inline <script> tag executed as part of parsing (the
 * page's IIFE runs top-to-bottom exactly as it would in a real browser -
 * see the module docstring above for why this is preferred over injecting
 * the script separately) and the jsdom gaps documented above stubbed in
 * `beforeParse`, which jsdom guarantees runs before ANY script in the
 * document - including transcript.js itself - has executed.
 *
 * @param {string} html
 * @returns {{window: any, document: any}}
 */
export function buildWindow(html) {
  const dom = new JSDOM(html, {
    url: 'https://transcript.test/transcript.html',
    runScripts: 'dangerously',
    resources: 'usable',
    pretendToBeVisual: true,
    beforeParse(window) {
      window.matchMedia = function (query) {
        return {
          media: query,
          matches: false,
          addListener() {},
          removeListener() {},
          addEventListener() {},
          removeEventListener() {},
          dispatchEvent() { return false; },
        };
      };
      window.HTMLElement.prototype.scrollIntoView = function () {};

      // jsdom never computes layout, so the real offsetParent getter (which
      // depends on it) always returns null - even for a plainly visible
      // element. focusableIn() (shared by the help panel's and the tour
      // card's own focus traps) filters out anything with a null
      // offsetParent specifically to skip [hidden]/display:none controls,
      // so leaving jsdom's always-null default in place would make every
      // trap think its container holds nothing focusable at all, no matter
      // what is actually in it. This approximates the real rule with the
      // one thing that actually varies in this app: whether a [hidden]
      // ancestor exists. It only touches HTMLElement.prototype - SVGElement
      // (the <use> icons inside toolbar buttons) has no offsetParent at all
      // in a real browser either, and is left with that same `undefined`
      // here.
      Object.defineProperty(window.HTMLElement.prototype, 'offsetParent', {
        configurable: true,
        get() { return this.closest('[hidden]') ? null : window.document.body; },
      });
    },
  });
  return { window: dom.window, document: dom.window.document };
}

/**
 * Stubs getBoundingClientRect on `el` (and, by extension, anything that
 * calls it) to a fixed, controlled box - the per-test replacement the
 * module docstring above says the shared jsdom-all-zeros default needs,
 * since positionDetachedMenu()/updateTourSpotlight() are meaningless
 * against an all-zero rect. `direction` is written onto the element's own
 * inline style (positionDetachedMenu reads getComputedStyle(target).direction,
 * not a DOM property) so RTL-clamp tests can flip it per call.
 *
 * @param {any} el
 * @param {{top?: number, left?: number, right?: number, bottom?: number, width?: number, height?: number}} box
 */
export function stubRect(el, box) {
  const top = box.top ?? 0;
  const left = box.left ?? 0;
  const width = box.width ?? ((box.right ?? left) - left);
  const height = box.height ?? ((box.bottom ?? top) - top);
  const right = box.right ?? (left + width);
  const bottom = box.bottom ?? (top + height);
  el.getBoundingClientRect = () => ({
    top, left, right, bottom, width, height, x: left, y: top,
    toJSON() { return this; },
  });
}
